# BigChainDB Remora Node Configuration

BIGCHAINDB_DATABASE_BACKEND = 'localmongodb'
BIGCHAINDB_DATABASE_HOST = 'localhost'
BIGCHAINDB_DATABASE_PORT = 27017
BIGCHAINDB_DATABASE_NAME = 'bigchain'
BIGCHAINDB_DATABASE_REPLICASET = 'bigchain-rs'

BIGCHAINDB_SERVER_BIND = '0.0.0.0:9984'
BIGCHAINDB_WSSERVER_HOST = '0.0.0.0'
BIGCHAINDB_WSSERVER_PORT = 9985

BIGCHAINDB_KEYPAIR_PUBLIC = None  # Will be set during initialization
BIGCHAINDB_KEYPAIR_PRIVATE = None

BIGCHAINDB_CONSENSUS_PLUGIN = 'default'